### ISSUE TITLE
The Meta Overlay generating a blank entry that should not be present

### ISSUE THREAD

**Issue by swcurran** [THCLab/oca-parser-xls#1]
I used the attached OCA Source file and when I generated the OCA Bundle (using https://browser.oca.argo.colossi.network/#/), the resulting Meta Overlay had a JSON entry of `"" : ""`.  Such entries should be suppressed in the output. The file was created by downloading the OCA Template from the OCA Browser, and then pasting in (values only) into the fields.

[ocatest.xlsx](https://github.com/THCLab/oca-rust/files/10340223/ocatest.xlsx)

For example, the "en-CA" Meta Overlay has this content:

```json
{
   "capture_base":"EKpcSmz06sJs0b4g24e0Jc7OerbJrGN2iMVEnwLYKBS8",
   "digest":"ERzcTK4SQCYv204QOm0r3wotG5JeMKvl0tcrC5TxMD14",
   "type":"spec/overlays/meta/1.0",
   "language":"en-CA",
   "name":"Person Credential",
   "description":"A Canadian schema used for the identity of a person",
   "":"",
   "issuer":"Government of British Columbia",
   "issuer_description":"Government of British Columbia",
   "issuer_url":"https://www.gov.bc.ca/"
}
```

**Comment by blelump** [comment]
@swcurran please check with the newer template: https://github.com/THCLab/oca-parser-xls/blob/main/templates/template.xlsx .

**Comment by olichwiruk** [comment]
With oca-rust [v0.2.23](https://github.com/THCLab/oca-rust/releases/tag/v0.2.23) and [online](https://browser.oca.argo.colossi.network/) works now.

That `"" : ""` entry in Meta overlays is caused by formulas in `Meta [Attribute Name]` and `Meta [Attribute Values]` columns that should be deleted, so the proper file looks like this: [ocatemplate.xlsx](https://github.com/THCLab/oca-parser-xls/files/10394029/ocatemplate.xlsx).

BTW: in `Main` sheet value defined as Format for `issuing_jurisdiction` attribute (cell F14) is actually Entry Codes, so it should be placed in cell G14.

**Comment by swcurran** [comment]
Confirmed -- thanks!  Updated the sheet to use Entry Codes a well -- thanks.
